version: '3'

services:

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/inventory
      SPRING_DATASOURCE_USERNAME: inventory
      SPRING_DATASOURCE_PASSWORD: inventory

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h database -U inventory"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

volumes:
  postgres_data:
